switch test
    case 'square_wave'
        % spquare wave
        problem = SSP_Tools.TestProblems.Advection('domain', [0, 1], ...
            'initial_condition', @(x)[ones(size(x(x<0))),zeros(size(x(x>=0)))],...
            'discretizer', dudx, ...
            'integrator', dudt, ...
            'N', N , 'a',1);
        
    case 'sine_wave'
        problem = SSP_Tools.TestProblems.Advection('domain', [0, 1], ...
            'initial_condition', @(x) sin(2*pi*x),...
            'discretizer', dudx, ...
            'integrator', dudt, ...
            'N', N , 'a',1);
        
    otherwise
        disp('not the right test')
end